// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

config({ path: ".env.local" });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // No `seed` command wired up: prisma/seed.ts was a one-time migration
    // from the old src/json/*.json files, which are now deleted (the
    // database is the source of truth). Kept in the repo as a historical
    // reference only — it would fail if re-run since those files are gone.
  },
  datasource: {
    // Migrations use the direct (unpooled) connection; the app's runtime
    // PrismaClient uses DATABASE_URL (pooled) via the Neon adapter instead.
    url: process.env["DIRECT_URL"],
  },
});
